# Generated by Django 3.2.9 on 2021-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonnas', '0002_alter_post_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
